#服务器端口
server:
  port: 8090

#连接数据库
spring:
  datasource:
    url: jdbc:mysql://101.133.238.241:3306/csdb?useUnicode=true&characeterEncoding=utf-8&useSSL=false&serverTimezone=UTC&
    #url: jdbc:mysql://127.0.0.1:3306/wtdb?useUnicode=true&characeterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wt123456
    #password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true

  #thymeleaf
  thymeleaf:
    encoding: UTF-8
    suffix: .html
    mode: LEGACYHTML5

#mybatis mapper
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    jdbc-type-for-null: NULL

#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true


# 上传图片的路径
image:
  logoPath: images/






